service: ddb-streams-test

frameworkVersion: "3"

provider:
  name: aws
  region: ${opt:region}
  runtime: nodejs14.x
  endpointType: REGIONAL
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"

resources:
  Resources:
    StreamsTestDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      #DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: pk 
            AttributeType: S
        KeySchema:
          -
            AttributeName: pk 
            KeyType: HASH
        #BillingMode: PAY_PER_REQUEST
        ProvisionedThroughput:
          ReadCapacityUnits: 100000
          WriteCapacityUnits: 1000000
        TableName: ddb-streams-test
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

#functions:
#  ddb-streams-test:
#    handler: handler.handler
#    environment:
#      TARGET_DDB_TABLE: ddb-streams-test
#    events:
#      - stream:
#         type: dynamodb
#         arn: arn:aws:dynamodb:us-east-2:284628898641:table/ddb-streams-test/stream/2023-03-13T21:20:40.678
#         batchSize: 25
#         parallelizationFactor: 10
#         startingPosition: TRIM_HORIZON
#         filterPatterns:
#           - eventName: [INSERT]
#             dynamodb:
#               NewImage:
#                 updateTime:
#                   [exists: false]
